[Active_Profile]
profile = 1

[Profile_DPIs]
profile_1 = 200
profile_2 = 600
profile_3 = 1200
profile_4 = 1600
profile_5 = 2400
profile_6 = 4000

[Profile_States]
profile_1 = 1
profile_2 = 1
profile_3 = 1
profile_4 = 1
profile_5 = 1
profile_6 = 1

[Profile_Colors]
profile_1 = rgb(255,73,0)
profile_2 = rgb(255,73,0)
profile_3 = rgb(255,53,0)
profile_4 = rgb(255,73,0)
profile_5 = rgb(255,73,0)
profile_6 = rgb(255,73,0)

[Color_Scheme]
type = Fixed
duration = 6

[Cyclic_Colors]
yellow = 0
blue = 0
violet = 0
green = 0
red = 0
cyan = 0
white = 0
